-- 0006: Static haber arşivini canlı D1 Haber CMS'e aktarır.
-- Kaynak: public/data/haberler.json + public/data/haber-kapaklari.json.
ALTER TABLE news ADD COLUMN source_url TEXT;
ALTER TABLE news ADD COLUMN original_date TEXT;
ALTER TABLE news ADD COLUMN archive_note TEXT;

INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('balikesir-in-en-kalabalik-pazari','Balıkesir''in En Kalabalık Pazarı','Balıkesir’in Cuma Pazarı, kentin en yoğun alışveriş noktalarından biri olarak sebze ve meyveden tekstile kadar geniş bir ürün çeşitliliği sunuyor. 4 Ekim 2024 tarihli saha haberinde pazarın yalnızca şehir merkezinden değil, çevre köylerden gelen üretici ve müşterileri de buluşturduğu aktarılıyordu.','Balıkesir’in Cuma Pazarı, kentin en yoğun alışveriş noktalarından biri olarak sebze ve meyveden tekstile kadar geniş bir ürün çeşitliliği sunuyor. 4 Ekim 2024 tarihli saha haberinde pazarın yalnızca şehir merkezinden değil, çevre köylerden gelen üretici ve müşterileri de buluşturduğu aktarılıyordu.

Haberin yapıldığı haftada tezgâhlarda domates 5-7 TL, salatalık 4-6 TL, patlıcan 10-12 TL, tatlı biber 8-10 TL, patates 7-9 TL ve soğan 6-8 TL aralığında görülüyordu. Sarımsak 40-45 TL, elma 12-15 TL, üzüm ise çeşidine göre 20-25 TL seviyesindeydi. Bu rakamlar 2024 tarihli arşiv fiyatlarıdır.

Pazarın dikkat çeken yönlerinden biri, köylü üreticilerin ürünlerini doğrudan tezgâha getirmesiydi. Peynir ve tereyağı gibi kahvaltılık ürünlerin yanı sıra zeytin, giyim ve mutfak gereçleri de aynı alanda satılıyordu. Akşam saatlerinde kalan ürünlerde indirim yapılması, pazarı özellikle bütçesini korumak isteyenler için cazip hale getiriyordu.

Cuma Pazarı, Balıkesir’de günlük ekonominin küçük bir fotoğrafını veriyor: üretici, esnaf ve tüketici aynı koridorda buluşuyor. Arşiv haberi de tam olarak bu hareketliliği ve 2024 sonbaharındaki fiyat görünümünü kayıt altına alıyor.','Yerel / Pazar','Buse Tuncay','/assets/haber-kapak/balikesir-in-en-kalabalik-pazari.webp','','published','2024-10-04T09:00:00+03:00','https://gazetemerhaba.com/balikesirin-en-kalabalik-pazari','04 Ekim 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-10-04T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('balikesir-de-berber-ve-kuafor-fiyatlari-el-yakiyor','Balıkesir’de Berber ve Kuaför Fiyatları El Yakıyor!','Balıkesir’de berber ve kuaför hizmetleri 2024 sonbaharında artan işletme giderlerinin etkisiyle belirgin biçimde pahalanmıştı. 2 Ekim 2024 tarihli haberde, erkek berberlerinden kadın kuaförlerine kadar farklı işletmelerle konuşularak kentteki fiyat değişimi ortaya konuldu.','Balıkesir’de berber ve kuaför hizmetleri 2024 sonbaharında artan işletme giderlerinin etkisiyle belirgin biçimde pahalanmıştı. 2 Ekim 2024 tarihli haberde, erkek berberlerinden kadın kuaförlerine kadar farklı işletmelerle konuşularak kentteki fiyat değişimi ortaya konuldu.

Paşaalanı’nda berberlik yapan Hakan Arıca, elektrik, su, kira ve bakım ürünlerindeki maliyet artışlarının tarifelere yansıdığını anlattı. O tarihte saç-sakal, yıkama ve fön dahil bazı paketler 400 TL’ye kadar çıkarken normal saç kesimi yaklaşık 250 TL, modelli kesim 260 TL ve sakal tıraşı 150 TL civarındaydı.

Düğün sezonunun özel kalemlerinden damat tıraşı Bahçelievler’de 1000 TL seviyesine ulaşmıştı. Kadın kuaförlerinde ise saç kesimi 250 TL, fön 200 TL, boya 800 TL, topuz 500 TL; röfle işlemleri saç uzunluğuna göre 1500-2000 TL aralığında veriliyordu. Bunlar 2024 tarihli arşiv fiyatlarıdır.

Esnaf, kaliteli ürün kullanma ve işletmeyi sürdürebilme zorunluluğunu vurgularken müşteriler artan hizmet bedellerinden şikâyet ediyordu. Haber, kişisel bakım sektöründe maliyet artışlarının tüketiciye nasıl yansıdığını yerel ölçekte belgeliyor.','Ekonomi / Yaşam','Buse Tuncay','/assets/haber-kapak/balikesir-de-berber-ve-kuafor-fiyatlari-el-yakiyor.webp','','published','2024-10-02T09:00:00+03:00','https://gazetemerhaba.com/balikesirde-berber-ve-kuafor-fiyatlari-el','02 Ekim 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-10-02T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('okul-doneminde-ayakkabicilar-carsisi-na-yogun-ilgi','Okul Döneminde Ayakkabıcılar Çarşısı''na Yoğun İlgi','Okulların açılması ve kış aylarının yaklaşması, Balıkesir Ayakkabıcılar Çarşısı’nda 2024 sonbaharında hareketliliği artırdı. 1 Ekim 2024 tarihli haberde, özellikle öğrenci ayakkabıları ve günlük spor modellerine yönelik talep öne çıktı.','Okulların açılması ve kış aylarının yaklaşması, Balıkesir Ayakkabıcılar Çarşısı’nda 2024 sonbaharında hareketliliği artırdı. 1 Ekim 2024 tarihli haberde, özellikle öğrenci ayakkabıları ve günlük spor modellerine yönelik talep öne çıktı.

Çarşı esnafından 78 yaşındaki Hikmet Karaman, öğrencilere yönelik ürünlerin 31 numaradan başlayıp 44-45 numaraya kadar uzandığını anlattı. Haberin yapıldığı dönemde çocuk ve okul ayakkabılarında yaklaşık 350-500 TL bandı, bazı ürünlerde ise 400 TL’den başlayan fiyatlar görülüyordu.

Gençlerin yoğun ilgi gösterdiği spor ayakkabılar kalite ve modele göre 600 TL’den başlayıp 1200 TL’ye kadar çıkıyordu. Beyaz ve siyah gibi kolay kombinlenen renkler en çok tercih edilenler arasındaydı.

Arşiv haberi, okul sezonunun yalnız kırtasiye değil ayakkabı esnafında da ayrı bir ekonomik hareket oluşturduğunu gösteriyor. Fiyatlar 2024’e aittir ve güncel tarife olarak değerlendirilmemelidir.','Yerel / Alışveriş','Buse Tuncay','/assets/haber-kapak/okul-doneminde-ayakkabicilar-carsisi-na-yogun-ilgi.webp','','published','2024-10-01T09:00:00+03:00','https://gazetemerhaba.com/okul-doneminde-ayakkabicilar-carsisina-yogun','01 Ekim 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-10-01T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('acikogretim-lisesi-ikinci-bir-sans-mi-yeni-zorluklar-mi','Açıköğretim Lisesi: İkinci Bir Şans mı, Yeni Zorluklar mı?','Örgün eğitimden açık liseye geçiş bazı öğrenciler için yeni bir başlangıç sunarken, süreç beraberinde maddi ve bürokratik sorunlar da getirebiliyor. 13 Eylül 2024 tarihli haberde Balıkesir’de yaşayan 16 yaşındaki Betül Tuncay’ın açıköğretim lisesine geçiş deneyimi üzerinden sistemin sahadaki etkileri ele alındı.','Örgün eğitimden açık liseye geçiş bazı öğrenciler için yeni bir başlangıç sunarken, süreç beraberinde maddi ve bürokratik sorunlar da getirebiliyor. 13 Eylül 2024 tarihli haberde Balıkesir’de yaşayan 16 yaşındaki Betül Tuncay’ın açıköğretim lisesine geçiş deneyimi üzerinden sistemin sahadaki etkileri ele alındı.

Tuncay, Hüma Hatun Kız Meslek Lisesi’nde iki dönem boyunca üç dersten kalmasının ardından örgün eğitim hakkını kaybettiğini, bu nedenle açık liseye yönelmek zorunda kaldığını anlattı. Mesleki açık lisede istediği bölüme geçememesi de seçeneklerini daraltan başlıklardan biri oldu.

Başvuru, kayıt, bölüm seçimi ve eğitim materyalleri gibi işlemler öğrenciler ve aileler için yalnızca idari değil ekonomik bir yük de oluşturabiliyor. Haberde, sistemin ''ikinci şans'' yaratmasının yanında öğrencinin bilgiye erişimi ve doğru yönlendirilmesi ihtiyacına da dikkat çekildi.

Bu arşiv haberi, eğitim politikalarının öğrencinin günlük hayatında nasıl karşılık bulduğunu bir genç öğrencinin deneyimi üzerinden görünür kılıyor.','Eğitim','Buse Tuncay','/assets/haber-kapak/acikogretim-lisesi-ikinci-bir-sans-mi-yeni-zorluklar-mi.webp','','published','2024-09-13T09:00:00+03:00','https://gazetemerhaba.com/acikogretim-lisesi-ikinci-bir-sans-mi-yeni','13 Eylül 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-09-13T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('balikesir-ali-suuri-pazari-nda-fiyatlar-ne-durumda','Balıkesir Ali Şuuri Pazarı''nda Fiyatlar Ne Durumda?','Balıkesir’in alışveriş noktalarından Ali Şuuri Pazarı, 29 Ağustos 2024 tarihli haberde giyimden çocuk ürünlerine kadar geniş bir fiyat taramasıyla ele alındı. Pazar, yerel halkın yanı sıra şehir dışından gelen ziyaretçilerin de uğrak noktalarından biri olarak öne çıkıyordu.','Balıkesir’in alışveriş noktalarından Ali Şuuri Pazarı, 29 Ağustos 2024 tarihli haberde giyimden çocuk ürünlerine kadar geniş bir fiyat taramasıyla ele alındı. Pazar, yerel halkın yanı sıra şehir dışından gelen ziyaretçilerin de uğrak noktalarından biri olarak öne çıkıyordu.

Kadın giyim tezgâhlarında tunik türü ürünler 650 TL’den, bazı takım elbiseler 750 TL’den satışa sunuluyordu. Erkek bölümünde şortlar yaklaşık 300 TL’den başlarken takım fiyatları 1500 TL’ye kadar çıkabiliyordu.

Pazarın en önemli avantajı, farklı bütçelere hitap eden çok sayıda satıcının aynı alanda bulunmasıydı. Alışveriş yapanlar fiyat karşılaştırmasını birkaç adım içinde yapabiliyor, pazarlık imkânı da klasik mağaza alışverişinden farklı bir esneklik sağlıyordu.

Haberdeki fiyatlar 2024 yaz sonuna aittir. Arşiv açısından değerli olan, Ali Şuuri Pazarı’nın o dönemde Balıkesir’deki perakende fiyatların ve tüketici davranışının canlı bir göstergesi olmasıdır.','Yerel / Pazar','Buse Tuncay','/assets/haber-kapak/balikesir-ali-suuri-pazari-nda-fiyatlar-ne-durumda.webp','','published','2024-08-29T09:00:00+03:00','https://gazetemerhaba.com/balikesir-ali-suuri-pazarinda-fiyatlar-ne','29 Ağustos 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-08-29T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('balikesir-in-gururu-memleketinde-sov-yapacak','Balıkesir''in Gururu Memleketinde Şov Yapacak!','Balıkesirli binici Şevket Sarıdemir, 6 Eylül 2024’te Halalca Mahallesi’nde düzenlenecek at binme etkinliği öncesinde memleketinde sahne almaya hazırlanıyordu. 26 Ağustos 2024 tarihli haber, Sarıdemir’in spor geçmişi ile Halalca’daki etkinliği bir araya getiriyordu.','Balıkesirli binici Şevket Sarıdemir, 6 Eylül 2024’te Halalca Mahallesi’nde düzenlenecek at binme etkinliği öncesinde memleketinde sahne almaya hazırlanıyordu. 26 Ağustos 2024 tarihli haber, Sarıdemir’in spor geçmişi ile Halalca’daki etkinliği bir araya getiriyordu.

Sarıdemir’in yurt içi ve yurt dışındaki yarışmalarda dereceler elde ettiği, özellikle Avrupa’daki organizasyonlarda Balıkesir’i temsil ettiği aktarılmıştı. Haberde ayrıca Fransa’da kazandığı birinciliğin kariyerindeki dikkat çekici sonuçlardan biri olduğu belirtiliyordu.

Halalca’daki organizasyon yalnız bir spor karşılaşması olarak değil, bölgedeki atçılık kültürünün tanıtılması açısından da önem taşıyordu. Etkinliğe çevre illerden katılım beklenirken, Sarıdemir kendi memleketinde yarışmanın kendisi için ayrı bir anlam taşıdığını ifade etmişti.

Arşiv haberi, yerel bir sporcunun uluslararası deneyimini doğduğu şehirdeki geleneksel bir etkinlikle buluşturan hikâyeyi kayıt altına alıyor.','Spor','Buse Tuncay','/assets/haber-kapak/balikesir-in-gururu-memleketinde-sov-yapacak.webp','','published','2024-08-26T09:00:00+03:00','https://gazetemerhaba.com/balikesirin-gururu-memleketinde-sov-yapacak','26 Ağustos 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-08-26T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('gayrimenkul-uzmani-uyardi','Gayrimenkul Uzmanı Uyardı!','Balıkesir’de 2024 yazında konut piyasasındaki durgunluk, yüksek faiz ve nakit ihtiyacı olan satıcıların oluşturduğu fırsatlar üzerinden tartışılıyordu. 26 Ağustos 2024 tarihli haberde gayrimenkul uzmanı Veli Göktepe, ev almak isteyenlere dönemin piyasa koşullarını değerlendirdi.','Balıkesir’de 2024 yazında konut piyasasındaki durgunluk, yüksek faiz ve nakit ihtiyacı olan satıcıların oluşturduğu fırsatlar üzerinden tartışılıyordu. 26 Ağustos 2024 tarihli haberde gayrimenkul uzmanı Veli Göktepe, ev almak isteyenlere dönemin piyasa koşullarını değerlendirdi.

Göktepe’ye göre yüksek faiz birçok alıcıyı beklemeye itmiş, bu da pazarlık gücünü alıcı lehine çevirmişti. Haberde 2,5 milyon TL değer biçilen bir konutun, sahibinin nakit ihtiyacı nedeniyle 1,5 milyon TL’ye satıldığı örneği aktarılmıştı.

Uzmanın temel görüşü, faizler düşmeden önce pazarlıkla uygun bir konut bulunabileceği; faizlerin gerilemesi halinde talebin ve dolayısıyla fiyatların hızla artabileceği yönündeydi. Özellikle gelişmekte olan bölgelerin uzun vadeli değer artışı potansiyeline dikkat çekiliyordu.

Bu haber 2024 piyasa koşullarını yansıtan bir arşiv çalışmasıdır; güncel yatırım tavsiyesi değildir. Bugünkü kararlar için güncel faiz, kredi ve bölgesel fiyat verileri ayrıca değerlendirilmelidir.','Ekonomi / Emlak','Buse Tuncay','/assets/haber-kapak/gayrimenkul-uzmani-uyardi.webp','','published','2024-08-26T09:00:00+03:00','https://gazetemerhaba.com/gayrimenkul-uzmani-uyardi','26 Ağustos 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-08-26T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('el-emegi-yorganlar-artik-isitmiyor','El Emeği Yorganlar Artık Isıtmıyor!','Balıkesir’in tarihi Mobilyacılar Çarşısı’nda el yapımı yorgancılık, 2024’te giderek azalan taleple mücadele eden geleneksel mesleklerden biriydi. 19 Ağustos 2024 tarihli görüntülü haberde, 12 yaşından beri yorgancılık yapan Mehmet Deniz’in dükkânı ve mesleğin geleceği anlatıldı.','Balıkesir’in tarihi Mobilyacılar Çarşısı’nda el yapımı yorgancılık, 2024’te giderek azalan taleple mücadele eden geleneksel mesleklerden biriydi. 19 Ağustos 2024 tarihli görüntülü haberde, 12 yaşından beri yorgancılık yapan Mehmet Deniz’in dükkânı ve mesleğin geleceği anlatıldı.

Deniz’in aktardığına göre bir yorganın tamamen elle dikilmesi yaklaşık iki gün sürüyordu. El emeğinin yoğun olması ve malzeme maliyetleri nedeniyle yorgan fiyatları o dönemde yaklaşık 1500 TL ile 3500 TL arasında değişiyordu.

Fabrikasyon ürünlerin yaygınlaşması, tüketicinin alışkanlıklarının değişmesi ve el işçiliğinin fiyatının yükselmesi, yorgancılığı giderek daha dar bir müşteri kitlesine sıkıştırıyordu. Buna rağmen ustalar, yıllardır öğrendikleri teknikleri sürdürerek geleneksel üretimi yaşatmaya çalışıyordu.

Haber, kaybolmaya yüz tutan bir zanaatı yalnız ekonomik açıdan değil kültürel hafıza açısından da görünür kılıyor. Sayfadaki video bağlantısı arşivde ayrıca korunmuştur.','Kültür / Zanaat','Buse Tuncay','/assets/haber-kapak/el-emegi-yorganlar-artik-isitmiyor.webp','https://www.youtube.com/watch?v=Gex7VqNEH7w','published','2024-08-19T09:00:00+03:00','https://gazetemerhaba.com/el-emegi-yorganlar-artik-isitmiyor','19 Ağustos 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-08-19T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('igneli-epilasyonun-bilinmeyen-riskleri','İğneli Epilasyonun Bilinmeyen Riskleri','İğneli epilasyon uzun süreli tüy azaltma amacıyla kullanılan yöntemlerden biri. Ancak 15 Ağustos 2024 tarihli haberde estetisyen Ecem Karavuş, uygulamanın eğitimli kişiler tarafından ve hijyen kurallarına uygun yapılmaması halinde ciltte iz ve tahriş gibi sorunlara yol açabileceğine dikkat çekti.','İğneli epilasyon uzun süreli tüy azaltma amacıyla kullanılan yöntemlerden biri. Ancak 15 Ağustos 2024 tarihli haberde estetisyen Ecem Karavuş, uygulamanın eğitimli kişiler tarafından ve hijyen kurallarına uygun yapılmaması halinde ciltte iz ve tahriş gibi sorunlara yol açabileceğine dikkat çekti.

Yöntemde her kıl kökü tek tek ince bir iğneyle hedefleniyor. Bu nedenle kullanılan iğnenin uygunluğu, uygulama derinliği, cihaz ayarı ve sterilizasyon işlemin güvenliği açısından kritik önem taşıyor. Karavuş, yanlış uygulamanın kalıcı skar riskini artırabileceğini belirtti.

Haberde altın iğne gibi daha ince seçeneklerin bazı uygulamalarda tercih edildiği, fakat asıl belirleyici unsurun uygulayıcının bilgisi ve hijyen standardı olduğu vurgulandı.

Bu arşiv içeriği tıbbi tavsiye yerine geçmez. Cilt hastalığı, aktif enfeksiyon veya özel bir sağlık durumu bulunan kişilerin uygulama öncesinde yetkili sağlık profesyoneline danışması gerekir.','Sağlık / Bakım','Buse Tuncay','/assets/haber-kapak/igneli-epilasyonun-bilinmeyen-riskleri.webp','','published','2024-08-15T09:00:00+03:00','https://gazetemerhaba.com/igneli-epilasyonun-bilinmeyen-riskleri','15 Ağustos 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-08-15T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('mangalin-yeni-gozdesi-istiridye-mantari','Mangalın Yeni Gözdesi: İstiridye Mantarı','İstiridye mantarı, 2024 yazında Balıkesir’de mangal sofralarında daha görünür hale gelen alternatif ürünlerden biri oldu. 15 Ağustos 2024 tarihli haberde Uzman Diyetisyen Hande Martin Bütün, mantarın besin değeri ve mutfaktaki kullanımına ilişkin değerlendirmelerde bulundu.','İstiridye mantarı, 2024 yazında Balıkesir’de mangal sofralarında daha görünür hale gelen alternatif ürünlerden biri oldu. 15 Ağustos 2024 tarihli haberde Uzman Diyetisyen Hande Martin Bütün, mantarın besin değeri ve mutfaktaki kullanımına ilişkin değerlendirmelerde bulundu.

Etli dokusu ve ızgaraya uygun yapısı nedeniyle istiridye mantarı, özellikle sebze ağırlıklı beslenenler için mangalda farklı bir seçenek sunuyor. Haberde protein içeriğiyle dikkat çektiği ve kırmızı et ya da tavuk yanında alternatif bir tabak oluşturabileceği anlatıldı.

Mantarın marinasyonla lezzetlendirilmesi, kısa sürede pişmesi ve sebzelerle birlikte servis edilebilmesi onu ev tipi mangal sofralarında pratik hale getiriyor. Yine de besin değerini doğrudan etle bire bir eşitlemek yerine porsiyon ve toplam beslenme düzeni içinde değerlendirmek daha doğru.

Arşiv haberi, Balıkesir’de değişen yemek alışkanlıklarının küçük ama ilginç bir örneğini kayda geçiriyor.','Gastronomi / Sağlık','Buse Tuncay','/assets/haber-kapak/mangalin-yeni-gozdesi-istiridye-mantari.webp','','published','2024-08-15T09:00:00+03:00','https://gazetemerhaba.com/mangalin-yeni-gozdesi-istiridye-mantari','15 Ağustos 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-08-15T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('balikesir-meyhaneler-bogazi-nda-pide-fiyatlari-ne-kadar','Balıkesir Meyhaneler Boğazı’nda Pide Fiyatları Ne Kadar?','Balıkesir Dumlupınar Mahallesi’ndeki Meyhaneler Boğazı, kentte pide ve fırın lezzetleri denince öne çıkan adreslerden biri. 8 Ağustos 2024 tarihli haberde, 2000 yılından bu yana hizmet veren Osman Melih Yıldırım’ın işletmesindeki fiyatlar ve bölgenin yeme içme kültürü ele alındı.','Balıkesir Dumlupınar Mahallesi’ndeki Meyhaneler Boğazı, kentte pide ve fırın lezzetleri denince öne çıkan adreslerden biri. 8 Ağustos 2024 tarihli haberde, 2000 yılından bu yana hizmet veren Osman Melih Yıldırım’ın işletmesindeki fiyatlar ve bölgenin yeme içme kültürü ele alındı.

O tarihte cantik 65 TL, lahmacun 70 TL, kıymalı pide 130 TL, kaşarlı pide 165 TL ve kuşbaşılı kaşarlı pide 180 TL olarak belirtilmişti. Kiremitte kaşarlı köfte 220 TL, karışık kiremit menemen ise 160 TL seviyesindeydi.

Yıldırım, fiyatlandırmada maliyet ile müşteri beklentisi arasında denge kurmaya çalıştıklarını anlatıyordu. Meyhaneler Boğazı’nın karakteristik yapısı da bölgedeki işletmelerin yalnız yemek değil, bir mahalle deneyimi sunmasına katkı sağlıyordu.

Fiyatlar 2024 arşiv değerleridir. Haber, Balıkesir’in yerel gastronomi noktalarından birinin o dönemki menü ve fiyat yapısını belgelemektedir.','Gastronomi','Buse Tuncay','/assets/haber-kapak/balikesir-meyhaneler-bogazi-nda-pide-fiyatlari-ne-kadar.webp','','published','2024-08-08T09:00:00+03:00','https://gazetemerhaba.com/balikesir-meyhaneler-bogazinda-pide-fiyatlari','08 Ağustos 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-08-08T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('balikesir-in-son-kalaycisi-ilyas-baykal','Balıkesir’in Son Kalaycısı: İlyas Baykal','Balıkesir Bakırcılar Çarşısı’nda yarım asrı aşan süredir çalışan İlyas Baykal, kentte kalaycılığı sürdüren son ustalardan biri olarak 7 Ağustos 2024 tarihli habere konu oldu.','Balıkesir Bakırcılar Çarşısı’nda yarım asrı aşan süredir çalışan İlyas Baykal, kentte kalaycılığı sürdüren son ustalardan biri olarak 7 Ağustos 2024 tarihli habere konu oldu.

Baykal, 12 yaşında başladığı mesleği 1967’den beri sürdürdüğünü anlattı. Balıkesir’in Gökköy köyünden merkeze geldiğinde farklı işlere yönelmeyi düşünürken, kalaycı olan ağabeylerinin etkisiyle bu zanaata adım attı.

Alüminyum ve çelik mutfak eşyalarının yaygınlaşması bakır kap kullanımını azaltınca kalaycılığa olan ihtiyaç da geriledi. Baykal’a göre usta olabilmek için yıllarca çıraklık yapmak gerekiyor; buna karşılık gençlerin mesleğe ilgisi giderek azalıyor.

Bu hikâye yalnız bir ustanın biyografisi değil, Balıkesir’in çarşı kültüründe yavaş yavaş kaybolan bir mesleğin hafıza kaydı niteliğinde.','Kültür / Zanaat','Buse Tuncay','/assets/haber-kapak/balikesir-in-son-kalaycisi-ilyas-baykal.webp','','published','2024-08-07T09:00:00+03:00','https://gazetemerhaba.com/balikesirin-son-kalaycisi-ilyas-baykal','07 Ağustos 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-08-07T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('balikesir-de-genclik-asisi-estetik-dunyasini-buyuluyor','Balıkesir''de Gençlik Aşısı Estetik Dünyasını Büyülüyor','Balıkesir’de estetik uygulamalar arasında gençlik aşısı adıyla bilinen hyaluronik asit temelli işlemler 2024 yazında ilgi görüyordu. 7 Ağustos 2024 tarihli haberde Dr. Özge Aydın, uygulamanın ne amaçla kullanıldığını ve sürecin nasıl ilerlediğini anlattı.','Balıkesir’de estetik uygulamalar arasında gençlik aşısı adıyla bilinen hyaluronik asit temelli işlemler 2024 yazında ilgi görüyordu. 7 Ağustos 2024 tarihli haberde Dr. Özge Aydın, uygulamanın ne amaçla kullanıldığını ve sürecin nasıl ilerlediğini anlattı.

Aydın’ın verdiği bilgilere göre işlem cilde hacim vermekten çok nem düzeyini desteklemeyi ve kolajen üretimini uyarmayı hedefliyor. Kullanılan ürünün içeriği, saflığı ve hangi cilt katmanına uygulanacağı sonucu etkileyen başlıklar arasında.

Haberde uygulamanın lokal anestezik krem sonrasında küçük iğnelerle yapıldığı, işlemin yaklaşık 10-15 dakika sürdüğü ve etkinin zaman içinde daha belirgin hale gelebildiği aktarılmıştı. Sauna ve hamam gibi yoğun sıcak ortamlardan bir süre kaçınma gibi işlem sonrası öneriler de yer aldı.

Bu içerik 2024 tarihli arşiv haberidir ve tıbbi öneri değildir. Estetik enjeksiyonlar sağlık profesyoneli değerlendirmesi ve kişiye özel uygunluk kontrolü gerektirir.','Sağlık / Estetik','Buse Tuncay','/assets/haber-kapak/balikesir-de-genclik-asisi-estetik-dunyasini-buyuluyor.webp','','published','2024-08-07T09:00:00+03:00','https://gazetemerhaba.com/balikesirde-genclik-asisi-estetik-dunyasi','07 Ağustos 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-08-07T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('gunes-koruyucu-seciminde-cilt-tipine-ozel-tavsiyeler','Güneş Koruyucu Seçiminde Cilt Tipine Özel Tavsiyeler','Güneşten korunma yalnız yaz tatilinde değil, günlük cilt bakımının da önemli parçalarından biri. 7 Ağustos 2024 tarihli haberde eczacı Esra Güven, güneş koruyucu seçerken cilt tipine göre farklı formüllerin tercih edilebileceğini anlattı.','Güneşten korunma yalnız yaz tatilinde değil, günlük cilt bakımının da önemli parçalarından biri. 7 Ağustos 2024 tarihli haberde eczacı Esra Güven, güneş koruyucu seçerken cilt tipine göre farklı formüllerin tercih edilebileceğini anlattı.

Akneye eğilimli ve yağlı ciltlerde gözenekleri ağırlaştırmayan, daha hafif ve matlaştırıcı ürünlerin; kuru ciltlerde ise nem desteği yüksek formüllerin öne çıktığı belirtildi. UVA ve UVB korumasının birlikte bulunması ve ürünün gün içinde yenilenmesi de temel noktalar arasında yer aldı.

Haberde bazı ürün örnekleri verilse de temel mesaj marka seçmekten çok cilt tipine, kullanım sıklığına ve güneşe maruz kalma süresine uygun koruma sağlamaktı.

Arşiv içeriği genel bilgilendirme amaçlıdır. Leke, akne, hassasiyet veya dermatolojik hastalık yaşayan kişilerin ürün seçimini dermatolog ya da eczacıyla birlikte yapması daha uygundur.','Sağlık / Bakım','Buse Tuncay','/assets/haber-kapak/gunes-koruyucu-seciminde-cilt-tipine-ozel-tavsiyeler.webp','','published','2024-08-07T09:00:00+03:00','https://gazetemerhaba.com/gunes-koruyucu-seciminde-cilt-tipine-tavsiyeler','07 Ağustos 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-08-07T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('balikesir-de-kira-fiyatlarinda-30-artis-bekleniyor','Balıkesir''de Kira Fiyatlarında %30 Artış Bekleniyor','2024 yazında üniversite yerleştirmeleri ve memur atamaları sonrasında Balıkesir’de kiralık konut talebinin artabileceği gündeme gelmişti. Buse Tuncay imzalı arşiv kaydında, talep artışının kira fiyatlarını yaklaşık yüzde 30 yukarı taşıyabileceği yönündeki beklenti aktarılıyordu.','2024 yazında üniversite yerleştirmeleri ve memur atamaları sonrasında Balıkesir’de kiralık konut talebinin artabileceği gündeme gelmişti. Buse Tuncay imzalı arşiv kaydında, talep artışının kira fiyatlarını yaklaşık yüzde 30 yukarı taşıyabileceği yönündeki beklenti aktarılıyordu.

Özellikle eğitim dönemi öncesinde öğrenci hareketliliği ile kamu personeli atamalarının aynı döneme denk gelmesi, merkezi mahallelerde ve ulaşımı kolay bölgelerde kiralık ev arayışını hızlandırabilecek etkenler olarak öne çıkıyordu.

Arşivde haberin başlığı ve özeti korunmuş durumda; ancak eski tekil kaynak bağlantısı bugün çalışmıyor. Bu nedenle BTmedya sürümünde haber, doğrulanabilen arşiv bilgisiyle ve açık bir kaynak notuyla yayımlanmalıdır.

Buradaki yüzde 30 ifadesi 2024 tarihli beklentidir, güncel kira artış oranı veya bugünkü piyasa tahmini değildir.','Ekonomi / Emlak','Buse Tuncay','/assets/haber-kapak/balikesir-de-kira-fiyatlarinda-30-artis-bekleniyor.webp','','published','2026-09-21T13:30:51.059Z','https://gazetemerhaba.com/etiket/buse-tuncay','Ağustos 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2026-09-21T13:30:51.059Z')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('balikesir-de-dugunlerin-vazgecilmez-dans-sarkilari','Balıkesir''de Düğünlerin Vazgeçilmez Dans Şarkıları','Balıkesir’de düğünlerin en duygusal anlarından biri olan ilk dans için çiftler hem modern hem nostaljik şarkılara yöneliyordu. 5 Ağustos 2024 tarihli kültür-yaşam haberi, kentte düğünlerde sık tercih edilen parçaları bir araya getirdi.','Balıkesir’de düğünlerin en duygusal anlarından biri olan ilk dans için çiftler hem modern hem nostaljik şarkılara yöneliyordu. 5 Ağustos 2024 tarihli kültür-yaşam haberi, kentte düğünlerde sık tercih edilen parçaları bir araya getirdi.

İlk dans listelerinde Eylem Aktaş’ın ''Yüreğimden Tut'' ve Sezen Aksu’nun ''Aşk'' parçaları öne çıkarken, Nilüfer’in ''Ta Uzak Yollardan'', Sezen Aksu’nun ''Hoşgeldin'', Özdemir Erdoğan’ın ''Bana Ellerini Ver'' ve Toygar Işıklı’nın ''Sen Yanımdayken'' şarkıları da romantik seçimler arasında gösteriliyordu.

Bu tercihler, düğün müziğinde tek bir modanın olmadığını; çiftlerin kendi hikâyelerine göre yeni ve eski parçaları aynı listede buluşturduğunu gösteriyor.

Arşiv haberi, 2024 düğün sezonunda Balıkesir’deki müzik zevkine küçük bir pencere açıyor.','Yaşam / Düğün','Buse Tuncay','/assets/haber-kapak/balikesir-de-dugunlerin-vazgecilmez-dans-sarkilari.webp','','published','2024-08-05T09:00:00+03:00','https://gazetemerhaba.com/balikesirde-dugunleri-vazgecilmez-dans-sarkilari','05 Ağustos 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-08-05T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('balikesir-esnafi-eleman-bulmakta-zorlaniyor','Balıkesir Esnafı Eleman Bulmakta Zorlanıyor','Balıkesir’de küçük işletmeler 2024 yazında en çok çalışan bulma ve çalışanı işte tutma sorunundan söz ediyordu. 1 Ağustos 2024 tarihli saha haberinde çiğköfteci, kebapçı, kafe, manav, pastane ve market işletmecileriyle görüşülerek iş gücü sıkıntısı farklı yönleriyle ele alındı.','Balıkesir’de küçük işletmeler 2024 yazında en çok çalışan bulma ve çalışanı işte tutma sorunundan söz ediyordu. 1 Ağustos 2024 tarihli saha haberinde çiğköfteci, kebapçı, kafe, manav, pastane ve market işletmecileriyle görüşülerek iş gücü sıkıntısı farklı yönleriyle ele alındı.

Esnafın ortak şikâyeti, uzun çalışma saatlerine karşı çalışanların daha yüksek ücret ve daha esnek koşullar talep etmesi; işe başlayan bazı kişilerin kısa sürede ayrılmasıydı. Bazı işletmeler günlük ödeme talebiyle karşılaştığını, bazıları ise aile bireyleriyle çalışmak zorunda kaldığını anlattı.

Kafe işletmecileri yemek desteği ve sözleşmeli çalışma gibi yöntemleri denerken, bazı esnaf kalıcı çalışan bulabilmek için asgari ücretin üzerinde ödeme yapmayı düşündüğünü söyledi. Buna karşılık çalışan tarafının uzun saatler ve düşük ücret nedeniyle işi sürdürememesi de tablonun diğer yüzüydü.

Haber, sorunu tek taraflı ''eleman yok'' cümlesine indirgemeden çalışma koşulları, ücret ve güven ilişkisi üzerinden yerel iş piyasasının gerilimini gösteriyor.','Ekonomi / Esnaf','Buse Tuncay','/assets/haber-kapak/balikesir-esnafi-eleman-bulmakta-zorlaniyor.webp','','published','2024-08-01T09:00:00+03:00','https://gazetemerhaba.com/balikesir-esnafi-eleman-bulmakta-zorlaniyor','01 Ağustos 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-08-01T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('balikesir-de-yaz-sicaklariyla-vantilator-satislari-patladi','Balıkesir''de Yaz Sıcaklarıyla Vantilatör Satışları Patladı','Balıkesir’de 2024 yaz sıcaklarının artmasıyla vantilatör ve hava serinletici ürünlere talep yükseldi. 30 Temmuz 2024 tarihli haberde elektronik mağazaları, züccaciyeler ve zincir marketlerdeki fiyat aralıkları karşılaştırıldı.','Balıkesir’de 2024 yaz sıcaklarının artmasıyla vantilatör ve hava serinletici ürünlere talep yükseldi. 30 Temmuz 2024 tarihli haberde elektronik mağazaları, züccaciyeler ve zincir marketlerdeki fiyat aralıkları karşılaştırıldı.

Temel ayaklı veya masa tipi vantilatörler yaklaşık 700-1400 TL bandında bulunabilirken, kule tipi, iyonizerli ya da hava soğutucu özellikli modeller daha yüksek fiyatlara çıkıyordu. Zincir marketlerde 799 TL’den başlayan modellerin yanı sıra 1999 TL civarında sanayi tipi seçenekler de vardı.

Esnaf, sıcak hava dalgasıyla birlikte satışların beklentinin üzerine çıktığını ifade ederken mağazalar kampanya ve indirimlerle rekabet etmeye çalışıyordu. Ücretsiz teslimat, ikinci üründe indirim gibi uygulamalar da satış stratejileri arasında yer alıyordu.

Fiyatlar Temmuz 2024 arşivine aittir. Haber, aşırı sıcakların yerel perakende talebini nasıl hızlı biçimde değiştirebildiğini gösteriyor.','Ekonomi / Yaşam','Buse Tuncay','/assets/haber-kapak/balikesir-de-yaz-sicaklariyla-vantilator-satislari-patladi.webp','','published','2024-07-30T09:00:00+03:00','https://gazetemerhaba.com/balikesirde-vantilator-satislari-patladi','30 Temmuz 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-07-30T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('kiralik-evlerde-yeni-donem-basliyor','Kiralık Evlerde Yeni Dönem Başlıyor','Balıkesir’de kiralık ev arayanların tercihleri 2024 yazında yalnız fiyatla sınırlı değildi. 17 Temmuz 2024 tarihli haberde emlakçı İlhan Ay, kiracıların deprem yönetmeliğine uygun, daha yeni ve güvenli binalara ilgisinin belirgin biçimde arttığını anlattı.','Balıkesir’de kiralık ev arayanların tercihleri 2024 yazında yalnız fiyatla sınırlı değildi. 17 Temmuz 2024 tarihli haberde emlakçı İlhan Ay, kiracıların deprem yönetmeliğine uygun, daha yeni ve güvenli binalara ilgisinin belirgin biçimde arttığını anlattı.

Son yıllarda yaşanan depremler kiracıların bina yaşı, yapı güvenliği ve konum gibi kriterleri daha fazla sorgulamasına neden olmuştu. Ev sahipleri açısından ise kiracı seçimi, ödeme düzeni ve sözleşme koşulları öne çıkan başlıklardı.

Haberde hem kiracıların hem ev sahiplerinin sözleşme öncesinde beklentileri açık biçimde konuşmasının, taşınmazın mevcut durumunu kayıt altına almasının ve yasal süreci takip etmesinin önemine dikkat çekiliyordu.

Bu içerik 2024 piyasa koşullarını anlatan arşiv haberidir. Güncel kira hukuku ve piyasa rakamları için yürürlükteki mevzuat ile güncel veriler ayrıca kontrol edilmelidir.','Ekonomi / Emlak','Buse Tuncay','/assets/haber-kapak/kiralik-evlerde-yeni-donem-basliyor.webp','','published','2024-07-17T09:00:00+03:00','https://gazetemerhaba.com/kiralik-evlerde-yeni-donem-basliyor','17 Temmuz 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-07-17T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('balikesir-in-gelin-ayakkabilari-ve-kina-terlikleri-modasi','Balıkesir''in Gelin Ayakkabıları ve Kına Terlikleri Modası','2024 düğün sezonunda Balıkesir’de gelin ayakkabıları ve kına terliklerinde taşlı, tüylü ve incili tasarımlar öne çıktı. 17 Temmuz 2024 tarihli haberde 23 yıllık sektör deneyimi bulunan Özer Özmelek, sezonun tercihlerini ve fiyatlarını anlattı.','2024 düğün sezonunda Balıkesir’de gelin ayakkabıları ve kına terliklerinde taşlı, tüylü ve incili tasarımlar öne çıktı. 17 Temmuz 2024 tarihli haberde 23 yıllık sektör deneyimi bulunan Özer Özmelek, sezonun tercihlerini ve fiyatlarını anlattı.

Kına terlikleri o dönemde yaklaşık 500-800 TL aralığında satılıyor, kullanılan malzeme ve işçiliğe göre bazı modeller 1000 TL’ye kadar çıkabiliyordu. Tüylü ve taşlı modeller kına gecelerinde en çok ilgi gören seçenekler arasındaydı.

Gelin ayakkabılarında ise fiyatlar modele, taş işlemelerine, platforma ve topuk yapısına göre 700 TL’den 1500 TL’ye kadar değişiyordu. Ortalama modeller 1000-1200 TL bandındaydı. İnci detaylı tasarımlar ve yaklaşık 10 santimetrelik orta topuklar, şıklık ile rahatlık arasında denge arayan gelinlerin tercihleri arasındaydı.

Fiyatlar 2024 sezonuna aittir. Arşiv haberi, Balıkesir’de düğün modasının ayrıntılarını küçük ama renkli bir perakende penceresinden gösteriyor.','Moda / Düğün','Buse Tuncay','/assets/haber-kapak/balikesir-in-gelin-ayakkabilari-ve-kina-terlikleri-modasi.webp','','published','2024-07-17T09:00:00+03:00','https://gazetemerhaba.com/gelin-ayakkabilari-ve-kina-terlikleri-modasi','17 Temmuz 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-07-17T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('balikesir-muay-thai-de-dunya-arenasinda','Balıkesir Muay Thai''de Dünya Arenasında','Balıkesirli Muay Thai sporcusu Hasan Buğra Kösüş, 16 Temmuz 2024 tarihli haberde sporun teknik yapısını, kültürel geçmişini ve profesyonel antrenman düzenini anlattı.','Balıkesirli Muay Thai sporcusu Hasan Buğra Kösüş, 16 Temmuz 2024 tarihli haberde sporun teknik yapısını, kültürel geçmişini ve profesyonel antrenman düzenini anlattı.

''Sekiz uzvun sanatı'' olarak bilinen Muay Thai; yumruk, tekme, diz ve dirsek tekniklerini birlikte kullanmasıyla diğer dövüş sporlarından ayrılıyor. Kösüş, özellikle baskılı dövüş stili ile diz ve dirsek tekniklerinin müsabaka stratejisinde önemli yer tuttuğunu belirtti.

Profesyonel sporcuların antrenman yükü oldukça yüksek. Haberde, hobi amaçlı çalışanların haftada birkaç gün antrenman yaparken profesyonellerin günlük koşu ve yaklaşık 1,5 saatlik teknik çalışmayı programlarına eklediği aktarılmıştı.

Haber, Muay Thai’yi yalnız sert bir dövüş sporu olarak değil disiplin, kondisyon ve kültür boyutlarıyla ele alıyor; Balıkesir’den uluslararası arenaya çıkan sporcuların hikâyesini de görünür kılıyor.','Spor','Buse Tuncay','/assets/haber-kapak/balikesir-muay-thai-de-dunya-arenasinda.webp','','published','2024-07-16T09:00:00+03:00','https://gazetemerhaba.com/balikesir-muay-thaide-dunya-arenasinda','16 Temmuz 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-07-16T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('kadin-firincidan-30-yillik-basari-oykusu','Kadın Fırıncıdan 30 Yıllık Başarı Öyküsü','Balıkesir Plevne Mahallesi’nde yaşayan Funda Şen, 15 yaşında başladığı fırıncılık mesleğinde 30 yılı geride bıraktığında 45 yaşındaydı. 12 Temmuz 2024 tarihli haber, Şen’in taş fırın başında geçen çalışma hayatını ve ailesiyle kurduğu üretim düzenini anlatıyordu.','Balıkesir Plevne Mahallesi’nde yaşayan Funda Şen, 15 yaşında başladığı fırıncılık mesleğinde 30 yılı geride bıraktığında 45 yaşındaydı. 12 Temmuz 2024 tarihli haber, Şen’in taş fırın başında geçen çalışma hayatını ve ailesiyle kurduğu üretim düzenini anlatıyordu.

Şen, babasından devraldığı yaklaşık 50 yıllık taş fırında eşi ve çocuklarıyla birlikte çalışıyor. Hamurun hazırlanmasından odun ateşinin kontrolüne kadar işin her aşamasında yer alması, onu Balıkesir’de nadir görülen kadın fırın ustalarından biri haline getirdi.

Fırında haşhaşlı ve cevizli çörek, kurabiye, poğaça, açma ve farklı tatlılar hazırlanıyor. Özellikle haşhaşlı çöreğin Balıkesirlilerden yoğun ilgi gördüğünü söyleyen Şen, geleneksel taş fırın yöntemini korumayı önemsiyor.

Yıllarca çalışarak çocuklarının eğitimine katkı sağlayan Şen’in hikâyesi, aile emeği, kadın girişimciliği ve geleneksel üretimin aynı fırında buluştuğu güçlü bir yerel portre.','İnsan Hikâyesi','Buse Tuncay','/assets/haber-kapak/kadin-firincidan-30-yillik-basari-oykusu.webp','','published','2024-07-12T09:00:00+03:00','https://gazetemerhaba.com/kadin-firincidan-30-yillik-basari-oykusu','12 Temmuz 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-07-12T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('diyetisyen-den-yaz-aylarinda-saglikli-beslenme-ve-hizli-zayiflama-sirlari','Diyetisyen''den Yaz Aylarında Sağlıklı Beslenme ve Hızlı Zayıflama Sırları','Yaz aylarında sıcaklık arttıkça beslenme ve sıvı tüketimi daha fazla önem kazanıyor. 22 Haziran 2024 tarihli haberde Diyetisyen Ayşe Gülova, sıcak havalarda dengeli beslenme, su tüketimi ve tatilde öğün seçimi üzerine öneriler paylaştı.','Yaz aylarında sıcaklık arttıkça beslenme ve sıvı tüketimi daha fazla önem kazanıyor. 22 Haziran 2024 tarihli haberde Diyetisyen Ayşe Gülova, sıcak havalarda dengeli beslenme, su tüketimi ve tatilde öğün seçimi üzerine öneriler paylaştı.

Gülova, günlük su tüketiminin kişiye göre değişmekle birlikte sıcak havada daha yakından takip edilmesi gerektiğini; karpuz, kavun, domates ve salatalık gibi su oranı yüksek yiyeceklerin sofraya eklenebileceğini anlattı. Şekerli ve çok kalorili içecekler yerine su, ayran ve benzeri seçeneklere ağırlık verilmesini önerdi.

Mangal ve dışarıda yemek gibi yaz rutinlerinde yağsız proteinler, bol sebze ve daha hafif pişirme yöntemleri öne çıkarıldı. Spor yapanlar için sıvı-elektrolit dengesi ile antrenman sonrası yeterli protein ve karbonhidrat alımının önemi hatırlatıldı.

Orijinal haberde örnek bir haftalık beslenme planı da yer alıyordu. Ancak kilo verme hedefleri kişiye özel olduğu için bu arşiv sürümünde plan reçete gibi sunulmuyor; beslenme programlarının diyetisyen değerlendirmesiyle kişiselleştirilmesi gerektiği özellikle belirtiliyor.','Sağlık / Beslenme','Buse Tuncay','/assets/haber-kapak/diyetisyen-den-yaz-aylarinda-saglikli-beslenme-ve-hizli-zayiflama-sirlari.webp','','published','2024-06-22T09:00:00+03:00','https://gazetemerhaba.com/diyetisyenden-yaz-aylarinda-saglikli-beslenme-ve-hizli-zayiflama-sirlari','22 Haziran 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-06-22T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('uzmanlardan-kilo-alma-ve-verme-stratejileri','Uzmanlardan Kilo Alma ve Verme Stratejileri','Sağlıklı biçimde kilo almak ya da vermek yalnız tartıdaki rakamı değiştirmekten ibaret değil. 29 Mayıs 2024 tarihli haberde antrenör Ahmet Öztürk ve sporcu Tolga Şahin, beslenme ile antrenman dengesini kendi deneyimleri üzerinden değerlendirdi.','Sağlıklı biçimde kilo almak ya da vermek yalnız tartıdaki rakamı değiştirmekten ibaret değil. 29 Mayıs 2024 tarihli haberde antrenör Ahmet Öztürk ve sporcu Tolga Şahin, beslenme ile antrenman dengesini kendi deneyimleri üzerinden değerlendirdi.

Öztürk, kilo vermek isteyenler için harcanandan daha az enerji alınmasının, kilo almak isteyenler için ise kontrollü bir kalori fazlasının temel prensip olduğunu anlattı. Her iki durumda da protein, karbonhidrat ve yağ dağılımının kişinin hedefi ve sağlık durumuna göre planlanması gerektiğini vurguladı.

Kilo alma sürecinde yalnız daha fazla yemek yerine kas kütlesini artırmaya yönelik direnç antrenmanı yapılması; kilo verme sürecinde de sürdürülebilir bir egzersiz ve beslenme düzeni oluşturulması öne çıkan mesajlardı.

Bu arşiv içeriği genel bilgilendirmedir. Kilo yönetimi özellikle kronik hastalık, yeme bozukluğu, metabolik sorun veya yoğun spor programı bulunan kişilerde sağlık profesyoneli eşliğinde planlanmalıdır.','Spor / Beslenme','Buse Tuncay','/assets/haber-kapak/uzmanlardan-kilo-alma-ve-verme-stratejileri.webp','','published','2024-05-29T09:00:00+03:00','https://gazetemerhaba.com/uzmanlardan-kilo-alma-ve-verme-stratejileri','29 Mayıs 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-05-29T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('sogan-tarlada-5-pazarda-15tl','Soğan Tarlada 5 Pazarda 15TL','Soğan ve patates fiyatlarındaki üretici-tüketici makası 28 Mayıs 2024 tarihli haberde pazar esnafı Hakan Seren’in değerlendirmeleriyle gündeme taşındı. Seren, soğanın sezon başında daha yüksek fiyatla satılırken tarlada 5 TL seviyesine kadar gerilediğini anlattı.','Soğan ve patates fiyatlarındaki üretici-tüketici makası 28 Mayıs 2024 tarihli haberde pazar esnafı Hakan Seren’in değerlendirmeleriyle gündeme taşındı. Seren, soğanın sezon başında daha yüksek fiyatla satılırken tarlada 5 TL seviyesine kadar gerilediğini anlattı.

Esnafın dikkat çektiği temel konu, tarladaki 5-6 TL’lik fiyat ile pazar ve markette 15-20 TL’ye ulaşan satış fiyatı arasındaki farktı. Seren, perakendecilerin alış ve satış fiyatlarının daha şeffaf olması gerektiğini savundu.

Patateste ise maliyetin yaklaşık 10 TL civarında olduğunu, bu nedenle fiyatın bunun altına düşmesinin üreticiyi zorlayacağını belirtti. 15-20 TL bandının sürdürülebilir olabileceğini, Bolu patatesinin ağustos sonundaki hasadıyla piyasanın yeniden şekillenebileceğini ifade etti.

12-13 yaşından beri patates, soğan ve sarımsak ticaretinin içinde olan Seren’in gözlemleri, 2024 ilkbaharında tarımsal fiyatların üreticiden tüketiciye uzanan zincirde nasıl değiştiğini gösteriyor.','Tarım / Ekonomi','Buse Tuncay','/assets/haber-kapak/sogan-tarlada-5-pazarda-15tl.webp','','published','2024-05-28T09:00:00+03:00','https://gazetemerhaba.com/sogan-tarlada-5-pazarda-15tl','28 Mayıs 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-05-28T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('balikesir-pazarinda-canli-helva-sovu','Balıkesir Pazarında Canlı Helva Şovu','Balıkesir Gümüşçeşme Mahallesi’nde kurulan Pazar Pazarı, 2 Mayıs 2024 tarihli görüntülü haberde geleneksel helva üretiminin sahneye dönüştüğü renkli bir tezgâha ev sahipliği yaptı. Helva ustası Mustafa Aybacı, ürünlerini müşterilerin gözü önünde hazırlayarak hem üretimi hem satışı aynı yerde buluşturuyordu.','Balıkesir Gümüşçeşme Mahallesi’nde kurulan Pazar Pazarı, 2 Mayıs 2024 tarihli görüntülü haberde geleneksel helva üretiminin sahneye dönüştüğü renkli bir tezgâha ev sahipliği yaptı. Helva ustası Mustafa Aybacı, ürünlerini müşterilerin gözü önünde hazırlayarak hem üretimi hem satışı aynı yerde buluşturuyordu.

Aybacı, aileden gelen helvacılık geleneğini sürdürdüğünü ve tahin helvası ile yaz helvası gibi çeşitleri kendi imalathanelerinde yaptıklarını anlattı. Üretimde şeker ve tahin temel malzemeler arasında yer alıyor; kıvamın tutturulması için karışımın tahta kaşık ve kürekle uzun süre işlenmesi gerekiyor.

O tarihte sekiz çeşit helva bulunduğu, sade ve kakaolu tahin helvasının yaklaşık 180 TL, yaz helvasının 120 TL, cevizli yaz helvasının 160 TL civarında satıldığı aktarılmıştı. Fiyatlar Mayıs 2024 arşivine aittir.

Bu haberin en güçlü yanı görüntüsü: geleneksel üretimin pazarda canlı biçimde yapılması. Video bağlantısı BTmedya arşiv paketine ayrıca eklendi.','Gastronomi / Video','Buse Tuncay','/assets/haber-kapak/balikesir-pazarinda-canli-helva-sovu.webp','https://www.youtube.com/watch?v=iaRHeI78TAk','published','2024-05-02T09:00:00+03:00','https://gazetemerhaba.com/balikesir-pazarinda-canli-helva-sovu','02 Mayıs 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-05-02T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
INSERT INTO news (slug,title,excerpt,body,category,author,cover_url,video_url,status,published_at,source_url,original_date,archive_note,updated_at)
VALUES ('beydonoglu-yaprak-satarken-festival-yonetiyor','Beydonoğlu Yaprak Satarken Festival Yönetiyor','Yaş sebze ve meyve ticareti ile hayvancılıkla uğraşan İsmail Beydonoğlu, 2 Mayıs 2024 tarihli görüntülü haberde hem taze yaprak ticaretini hem de bölgesel festival çalışmalarını anlattı.','Yaş sebze ve meyve ticareti ile hayvancılıkla uğraşan İsmail Beydonoğlu, 2 Mayıs 2024 tarihli görüntülü haberde hem taze yaprak ticaretini hem de bölgesel festival çalışmalarını anlattı.

Manisa Alaşehir çevresinden temin edilen taze asma yapraklarını farklı illerde müşterilere ulaştıran Beydonoğlu, üreticiden mümkün olduğunca yüksek fiyatla alıp tüketiciye uygun fiyatla satmaya çalıştığını söyledi. O tarihte yaprağın kilosu yaklaşık 75 TL, üç kilosu 200 TL olarak belirtilmişti.

Ticaretin yanında etkinlik organizasyonlarına da ağırlık veren Beydonoğlu, Turgutlu’da kiraz festivali hazırlıkları yaptığını, Balıkesir Pamukçu’da ise sarımsak festivali düzenleme fikrini gündeme getirdiğini anlattı.

Haber, bir esnafın günlük ticaretinin yerel ürünleri tanıtan festivaller ve sosyal girişimlerle nasıl birleşebildiğini gösteriyor. Görüntülü haberin YouTube bağlantısı paket içinde korunmuştur.','Tarım / Etkinlik / Video','Buse Tuncay','/assets/haber-kapak/beydonoglu-yaprak-satarken-festival-yonetiyor.webp','https://www.youtube.com/watch?v=1c70ybbtjYk','published','2024-05-02T09:00:00+03:00','https://gazetemerhaba.com/beydonoglu-yaprak-satarken-festival-yonetiyor','02 Mayıs 2024','BTmedya için yeniden yazılmış arşiv sürümü. Orijinal yayın bilgileri korunmuştur.','2024-05-02T09:00:00+03:00')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title,excerpt=excluded.excerpt,body=excluded.body,category=excluded.category,author=excluded.author,cover_url=excluded.cover_url,video_url=CASE WHEN excluded.video_url<>'' THEN excluded.video_url ELSE news.video_url END,status='published',published_at=COALESCE(news.published_at,excluded.published_at),source_url=excluded.source_url,original_date=excluded.original_date,archive_note=excluded.archive_note,updated_at=excluded.updated_at;
