/* BTMEDYA Site OS — multi-client website control plane. */
const j=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const now=()=>new Date().toISOString();
const sec=e=>{const x=e?.ADMIN_SESSION_SECRET_SECRET||e?.ADMIN_SESSION_SECRET||'';return x?(e?.MEDIA_SIGNING_SECRET?x+'\u0000'+e.MEDIA_SIGNING_SECRET:x):''};
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function hmac(s,m){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(s),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(m)))}
async function auth(r,e){const s=sec(e),c=r.headers.get('cookie')||'',m=c.match(/bt_admin=([^;]+)/);if(!s||!m)return false;const [p,sg]=m[1].split('.');try{if(sg!==await hmac(s,p))return false;let q=p.replace(/-/g,'+').replace(/_/g,'/');while(q.length%4)q+='=';return JSON.parse(atob(q).split('').map(x=>String.fromCharCode(x.charCodeAt(0))).join('')).exp>Date.now()}catch{return false}}
async function ensure(e){if(!e.DB)return;await e.DB.prepare(`CREATE TABLE IF NOT EXISTS client_sites(id TEXT PRIMARY KEY,client_id TEXT NOT NULL,name TEXT NOT NULL,slug TEXT NOT NULL,domain TEXT NOT NULL DEFAULT '',website_url TEXT NOT NULL DEFAULT '',platform TEXT NOT NULL DEFAULT 'cloudflare',hosting_provider TEXT NOT NULL DEFAULT 'cloudflare',repo_full_name TEXT NOT NULL DEFAULT '',repo_branch TEXT NOT NULL DEFAULT 'main',deployment_provider TEXT NOT NULL DEFAULT 'github',deployment_ref TEXT NOT NULL DEFAULT '',analytics_provider TEXT NOT NULL DEFAULT 'cloudflare_web_analytics',analytics_ref TEXT NOT NULL DEFAULT '',gsc_property TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'active',health_status TEXT NOT NULL DEFAULT 'unknown',last_check_at TEXT,last_deploy_at TEXT,last_error TEXT NOT NULL DEFAULT '',settings_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(client_id,slug))`).run().catch(()=>{});await e.DB.prepare(`CREATE TABLE IF NOT EXISTS client_site_checks(id TEXT PRIMARY KEY,site_id TEXT NOT NULL,check_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'unknown',score INTEGER,detail TEXT NOT NULL DEFAULT '',checked_at TEXT NOT NULL)`).run().catch(()=>{});await e.DB.prepare(`CREATE TABLE IF NOT EXISTS client_site_jobs(id TEXT PRIMARY KEY,site_id TEXT NOT NULL,job_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',run_after TEXT,attempts INTEGER NOT NULL DEFAULT 0,payload_json TEXT NOT NULL DEFAULT '{}',last_error TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`).run().catch(()=>{})}
async function check(e,s){const u=String(s.website_url||s.domain||'').trim();if(!/^https?:\/\//i.test(u))return{status:'error',score:0,detail:'Geçerli website_url yok'};const t=Date.now();try{const r=await fetch(u,{redirect:'follow',headers:{'User-Agent':'BTMEDYA-SiteOS/1.0'}}),h=(await r.text()).slice(0,500000),a=/<title[^>]*>[^<]{2,}/i.test(h),d=/<meta[^>]+name=["']description["'][^>]+content=/i.test(h),c=/<link[^>]+rel=["']canonical["']/i.test(h),v=/<meta[^>]+name=["']viewport["']/i.test(h),score=[r.ok,a,d,c,v].filter(Boolean).length*20;return{status:r.ok&&score>=80?'healthy':r.ok?'warning':'error',score,detail:`HTTP ${r.status}; title=${a}; description=${d}; canonical=${c}; viewport=${v}; ${Date.now()-t}ms`}}catch(x){return{status:'error',score:0,detail:String(x?.message||x).slice(0,300)}}}
export async function siteOsApi(r,e,u){if(!u.pathname.startsWith('/api/admin/site-os'))return null;if(!(await auth(r,e)))return j({ok:false,error:'Yetkisiz'},401);if(!e.DB)return j({ok:false,error:'D1 yapılandırılmadı'},503);await ensure(e);
if(u.pathname==='/api/admin/site-os'&&r.method==='GET'){const z=(await e.DB.prepare(`SELECT s.*,c.name client_name,c.slug client_slug FROM client_sites s LEFT JOIN client_workspaces c ON c.id=s.client_id ORDER BY c.name,s.name`).all()).results||[];return j({ok:true,items:z,summary:{total:z.length,healthy:z.filter(x=>x.health_status==='healthy').length,warning:z.filter(x=>x.health_status==='warning').length,error:z.filter(x=>x.health_status==='error').length,unknown:z.filter(x=>x.health_status==='unknown').length}})}
if(u.pathname==='/api/admin/site-os'&&r.method==='POST'){const b=await r.json().catch(()=>({}));if(!b.client_id||!b.name)return j({ok:false,error:'client_id ve name zorunlu'},400);const t=now(),id=crypto.randomUUID(),slug=String(b.slug||b.name).toLowerCase().trim().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)||id.slice(0,8);await e.DB.prepare(`INSERT INTO client_sites(id,client_id,name,slug,domain,website_url,platform,hosting_provider,repo_full_name,repo_branch,deployment_provider,analytics_provider,analytics_ref,gsc_property,status,health_status,last_check_at,last_deploy_at,last_error,settings_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,b.client_id,b.name,slug,b.domain||'',b.website_url||b.domain||'',b.platform||'cloudflare',b.hosting_provider||'cloudflare',b.repo_full_name||'',b.repo_branch||'main',b.deployment_provider||'github',b.analytics_provider||'cloudflare_web_analytics',b.analytics_ref||'',b.gsc_property||'','active','unknown',null,null,'',JSON.stringify(b.settings||{}),t,t).run();return j({ok:true,id,slug},201)}
const cm=u.pathname.match(/^\/api\/admin\/site-os\/([^/]+)\/check$/);if(cm&&r.method==='POST'){const s=await e.DB.prepare('SELECT * FROM client_sites WHERE id=? OR slug=? LIMIT 1').bind(cm[1],cm[1]).first();if(!s)return j({ok:false,error:'Site bulunamadı'},404);const o=await check(e,s),t=now();await e.DB.prepare('INSERT INTO client_site_checks(id,site_id,check_type,status,score,detail,checked_at) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),s.id,'http-seo',o.status,o.score,o.detail,t).run();await e.DB.prepare('UPDATE client_sites SET health_status=?,last_check_at=?,last_error=?,updated_at=? WHERE id=?').bind(o.status,t,o.status==='error'?o.detail:'',t,s.id).run();return j({ok:true,site_id:s.id,...o,checked_at:t})}
const m=u.pathname.match(/^\/api\/admin\/site-os\/([^/]+)$/);if(m&&r.method==='GET'){const s=await e.DB.prepare('SELECT s.*,c.name client_name,c.slug client_slug FROM client_sites s LEFT JOIN client_workspaces c ON c.id=s.client_id WHERE s.id=? OR s.slug=? LIMIT 1').bind(m[1],m[1]).first();if(!s)return j({ok:false,error:'Site bulunamadı'},404);const checks=(await e.DB.prepare('SELECT * FROM client_site_checks WHERE site_id=? ORDER BY checked_at DESC LIMIT 50').bind(s.id).all()).results||[],jobs=(await e.DB.prepare('SELECT * FROM client_site_jobs WHERE site_id=? ORDER BY created_at DESC LIMIT 50').bind(s.id).all()).results||[];return j({ok:true,site:s,checks,jobs})}
return j({ok:false,error:'Site OS endpoint bulunamadı'},404)}
export async function runSiteOsChecks(env,{limit=20}={}){if(!env?.DB)return{ok:false,reason:'D1 yok'};await ensure(env);const clients=(await env.DB.prepare("SELECT id,name,slug,website_url FROM client_workspaces WHERE status='active' AND web_management_enabled=1 AND website_url!=''").all()).results||[];let created=0,checked=0,errors=0;for(const cl of clients){let site=await env.DB.prepare("SELECT * FROM client_sites WHERE client_id=? ORDER BY updated_at DESC LIMIT 1").bind(cl.id).first();if(!site){const t=now(),id=crypto.randomUUID(),slug=String(cl.slug||cl.name||id).toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70)||id.slice(0,8);await env.DB.prepare("INSERT INTO client_sites(id,client_id,name,slug,domain,website_url,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)").bind(id,cl.id,cl.name,slug,new URL(cl.website_url).hostname,cl.website_url,t,t).run().catch(()=>{});site=await env.DB.prepare("SELECT * FROM client_sites WHERE id=?").bind(id).first();created++}if(checked>=limit)break;const o=await check(env,site);const t=now();await env.DB.prepare("INSERT INTO client_site_checks(id,site_id,check_type,status,score,detail,checked_at) VALUES(?,?,?,?,?,?,?)").bind(crypto.randomUUID(),site.id,'http-seo',o.status,o.score,o.detail,t).run().catch(()=>{errors++});await env.DB.prepare("UPDATE client_sites SET health_status=?,last_check_at=?,last_error=?,updated_at=? WHERE id=?").bind(o.status,t,o.status==='error'?o.detail:'',t,site.id).run().catch(()=>{errors++});checked++}return{ok:true,clients:clients.length,created,checked,errors}}
